server:
  port: 9991

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=UTF-8  #?useUnicode=true&characterEncoding=UTF-8  	解决前台数据插入后台不乱码
    username: root
    password: root


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10088/eureka # default写错 ！！！

  #保证拿到的一定是ip
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper-locations: mapper/*.xml